name: Generate SBOM for Dependencies

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate SBOM using Syft (for project dependencies)
      uses: anchore/sbom-action@v0
      with:
        format: spdx-json
        output-file: sbom.spdx.json
        #image: "dir:."


    - name: Upload SBOM as artifact
      uses: actions/upload-artifact@v3
      with:
        name: sbom-dependencies
        path: sbom.spdx.json
