name: Generate SBOM for Dependencies

on:
  push:
    branches: ["*"]
jobs:
  generate-sbom:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate SBOM using Syft
      uses: anchore/sbom-action@v0
      with:
        format: spdx-json
        output-file: sbom.spdx.json
        image: "dir:." 

    - name: Upload SBOM artifact (v4)
      uses: actions/upload-artifact@v4
      with:
        name: sbom-dependencies
        path: sbom.spdx.json
