name: Generate SBOM for Dependencies

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  generate-sbom:
    runs-on: ubuntu-22.04  # Explicitly use current LTS to avoid future ubuntu-24.04 warnings

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate SBOM using Syft
      uses: anchore/sbom-action@v0
      with:
        format: spdx-json
        output-file: sbom.spdx.json
        image: "sbom-dependencies:."
