name: Semgrep
on:
  pull_request: {}
  push:
    branches:
      - "*"
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: {}
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Semgrep scan
        id: scan
        continue-on-error: true  # Continue to generate reports even if issues found
        run: semgrep ci --config=auto --sarif -o result.sarif

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4

      - name: Generate reports
        run: |
          cat << 'EOF' > generate_reports.py
          import json
          import csv
          from bs4 import BeautifulSoup

          # (Keep your full Python script here)

          generate_sarif_html_and_csv("result.sarif", "report.html", "report.csv")
          EOF
          python generate_reports.py

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results
          path: |
            result.sarif
            report.html
            report.csv

      - name: Fail if issues found
        if: steps.scan.outcome == 'failure'
        run: exit 1
