name: Semgrep Security Scan

on:
  push:
    branches: [ '*' ]

jobs:
  semgrep-scan:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v2
        with:
          config: p/ci
          output: semgrep-results.sarif
          args: --sarif --metrics=off --error
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif
